### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by ORESoftware** [bubkoo/ascii-progress#11]
Got this error:

```js
 => Suman fatal error (domain caught) => TypeError: Cannot read property 'row' of undefined
    at Socket.<anonymous> (/Users/Olegzandr/WebstormProjects/oresoftware/suman/node_modules/node-progress-bars/index.js:34:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.stream.write (/Users/Olegzandr/WebstormProjects/oresoftware/suman/node_modules/on-new-line/index.js:49:14)
    at Object.runnerLog [as log] (/Users/Olegzandr/WebstormProjects/oresoftware/suman/lib/sync-logger.js:22:24)
    at runSingleOrMultipleDirs (/Users/Olegzandr/WebstormProjects/oresoftware/suman/lib/runner.js:1129:22)
    at /Users/Olegzandr/WebstormProjects/oresoftware/suman/lib/runner.js:1166:13
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

/Users/Olegzandr/WebstormProjects/oresoftware/suman/node_modules/node-progress-bars/index.js:34
  if (current.row < stream.rows) {
             ^

TypeError: Cannot read property 'row' of undefined
    at Socket.<anonymous> (/Users/Olegzandr/WebstormProjects/oresoftware/suman/node_modules/node-progress-bars/index.js:34:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.stream.write (/Users/Olegzandr/WebstormProjects/oresoftware/suman/node_modules/on-new-line/index.js:49:14)
    at process.<anonymous> (/Users/Olegzandr/WebstormProjects/oresoftware/suman/lib/handle-exit.js:47:28)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:146:15)
    at Domain.<anonymous> (/Users/Olegzandr/WebstormProjects/oresoftware/suman/lib/run.js:185:15)
    at Domain.g (events.js:286:16)

```

via this code:

```js
//core
const util = require('util');

//npm
const ProgressBar = require('node-progress-bars');
const suman = require('suman');

////////////////////////////////////////


module.exports = s => {

  var progressBar;

  s.on('runner-started', function onRunnerStart (totalNumTests) {

    progressBar = new ProgressBar({
      schema: ':bar',
      total: 10
    });

  });


  s.on('test-end', function onTestEnd () {
    progressBar.tick();
  });

  s.on('runner-end', function onRunnerEnd () {

  });

  s.on('suite-skipped', function onRunnerEnd () {

  });

  s.on('suite-end', function onRunnerEnd () {

  });

};
```

**Comment by ORESoftware** [comment]
also, it would be nice to be able to do this:

``` js
//core
const util = require('util');

//npm
const ProgressBar = require('node-progress-bars');
const suman = require('suman');

////////////////////////////////////////


module.exports = s => {

  const progressBar = new ProgressBar({
      schema: ':bar'
    });

  s.on('runner-started', function onRunnerStart (totalNumTests) {
       progressBar.setTotal(totalNumTests).start();
  });


  s.on('test-end', function onTestEnd () {
       progressBar.tick();
  });

  s.on('runner-end', function onRunnerEnd () {

  });

  s.on('suite-skipped', function onRunnerEnd () {

  });

  s.on('suite-end', function onRunnerEnd () {

  });

};
```

that code is just a little better
