### ISSUE TITLE
Error after basic npm i

### ISSUE THREAD

**Issue by nickshevr** [bubkoo/ascii-progress#12]
```
nickshevr@nickshevr-work:~/CloudTech/smarty-migrate$ npm i --save-dev ascii-progress

> get-cursor-position@1.0.3 install /home/nickshevr/CloudTech/smarty-migrate/node_modules/ascii-progress/node_modules/get-cursor-position
> node-gyp rebuild

make: Entering directory '/home/nickshevr/CloudTech/smarty-migrate/node_modules/ascii-progress/node_modules/get-cursor-position/build'
  CXX(target) Release/obj.target/pos/src/pos.o
../src/pos.cc: In function ‘void Method(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/pos.cc:259:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  int ret, row, col;
      ^
  SOLINK_MODULE(target) Release/obj.target/pos.node
  COPY Release/pos.node
make: Leaving directory '/home/nickshevr/CloudTech/smarty-migrate/node_modules/ascii-progress/node_modules/get-cursor-position/build'
smarty-migrate@0.0.1 /home/nickshevr/CloudTech/smarty-migrate
├─┬ ascii-progress@1.0.5 
│ └── get-cursor-position@1.0.3 
└── UNMET PEER DEPENDENCY eslint@3.9.1
npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm WARN smarty-migrate@0.0.1 No repository field.
```

After this I start nodeJS script:

```
nickshevr@nickshevr-work:~/CloudTech/smarty-migrate$ node ./migrations/001-newChatModelMigrate.js 
module.js:457
    throw err;
    ^

Error: Cannot find module './build/release/pos'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nickshevr/CloudTech/smarty-migrate/node_modules/get-cursor-position/index.js:1:74)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nickshevr/CloudTech/smarty-migrate/node_modules/node-progress-bars/index.js:4:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nickshevr/CloudTech/smarty-migrate/migrations/001-newChatModelMigrate.js:5:21)
    at Module._compile (module.js:556:32)
```

**Comment by nickshevr** [comment]
I fixed it, np
