### ISSUE TITLE
Cannot find module './build/release/pos'

### ISSUE THREAD

**Issue by RafaelKr** [bubkoo/ascii-progress#2]
Edit 2: This error is already fixed by a Pull Request for get-cursor-position:
https://github.com/bubkoo/get-cursor-position/pull/1/commits/09b40139627c16561f53fe00646d3aeb30eb98dd

I get this error:

```
Error: Cannot find module './build/release/pos'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ascii-progress/node_modules/get-cursor-position/index.js:1:74)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

Edit: I'm using node.js v6.0.0

**Comment by bubkoo** [comment]
@RafaelKr Merged and bump to v1.0.2
